language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.0
  - android-26
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
- openssl aes-256-cbc -K $encrypted_62ed174ed142_key -iv $encrypted_62ed174ed142_iv
  -in obm.keystore.enc -out obm.keystore -d

install: ./gradlew clean
script: ./gradlew assembleProd

deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  api_key:
    secure: qkShQEWmLJZJow/TWHoxyGwNXKlAxKAx/aUwuOUOArkSWfTPg1EBmRNp5C4lht8TJunOppSjhS37AcLp1VPHggioh+YU1q3kkA+OxWpTeweEQOYTyI5FO64glH2dHHZXR/JrQ4GwGKw8CaAJXqqvTEXW6bFZY5U82sAgERmeCKL0/1rkF4x+NeqFF8/GUce2UGTOcQlsSDh7vefHEA6ga9FaTdIIBULvrMMMng0jSR9lg2i1MwQh8oXlMZXodL/4KLbF7f9PNqd+2YupuV4BMtOdNYHOv3t0ZLmiqfoziTKC6xjW2AZpMpZUBEkPlTjDsV9sBqiTuXxq2uJLSFzdeWgoiFcZvWwsrKzzyOg7F4lUkkrNd2ykVd0wORhbwpA6ndx+3mJz63bjPMdlFMQ/DY1Goy4eR8HFA1l8acaf7YRUMf8BM7fn5b9uFu7h2OLHSoz5gpUEEexnqcRVIgmIGAQDyRDOkDz8wn8qy0TonwTSkBS4VAlv3lnkCuLrHSdaKjVd58ryB+5rf1Y+MgEEUy1vtqDWk7IGldTBop290idKitRtFyhRF5hS5oFYDKwx2ivJ8ADu42HG2yNQmljLhrQL1rPSqcg+9tpsTqS7kWeWlhMC/2Dgau79QjqHeXUdclHzN+t6HwEdte8Uv2r0xNb6u/A76/BQu8py/mVyC2E=
  file: app/build/outputs/apk/app-prod-release.apk
  on:
    all_branches: true
    tag: true

env:
  global:
  - secure: qGkZcURoFunXdgUoe9qBIf8hgoNCjUUYCOC0C/qkT3t+hfSVJdxtZqU8kHgihz2OeecmHBFF53VEbgOkNAsEXabfvSgCEfW80CWlbEdiwUdOWQ8xLG5cwK5hxU7VHYELj03X9AqiVDoAdLQ6m0OWJA7xazQ1o43zuSUcSuMRrd4ktVwc1Uu2UnIoeec05t70seNueln7+aQb9hV0URwmFB1OGZln3bOjllRkOD8Yhx6xK2LnM/CNLYJAal+2BCmt9GPnsLVWFmjjyUpdp9so3MIIvaibMg/mJSe/hP8UXVwkPeOQjV/iPDywmaFr+dM3Gylxnh2J20xRmifIUhBw+C9ybKkwutv6zjlZPwgnCLK37S4v/U/OO5YXSbZ4PkHOviLq24hBiV0oQCYToMnK1V1yaQgt2k5BJrW02MlmK1eDn0TqwnQB1omJ8trclZNi/CURJrcIFzEsBWmVzP3GVw9N9IwH7p7BeMvj+54GtKotFanJB2DoJdSRTguMdTU1ultHDxuJZD1x23JWdo89IE7B+6CN+/2Wbe2QW4K088nOIYxJRjmIKxwMB30sG8iMebau6aZPGtofefTf8XqbbUjyiFSM12VFP5INJgypUYdW0LkTZVMl12TJ/vOV6dMMjnBydTl6tiz+jWLTsTYeuHHHl3iB4rWGEsiw9CKiccE=
  - secure: hGF5SwC2ZTvJNgDfWAgwLU3A0lOL354DTTg/RwMr9vMUEpVJEKdyVnKsemucRC1/v/1neLELLt471Uad4aFPG69QmEeq2OyZWmbchrXUuReosBwLGctGCyd+ESPEsUyblBrBnrDYo96bmB35gw4Th2J7kwtVtp0qOgwzbJEbZvsocXxHFQ9thjh7rKibLeqEeFmvkS8HdH9V6cZfqB7pA1TFlh+5aDXje5Q9ssubiteSPkKMHPWXN0Cq7Bz4XTDIN5zEN9iEyaMlD5p+/Q+VPw2GTjF8SP1t8YQyBMTjStUYLMMgkLcevSBWTk4dVNDIcmBP4gESxAUXzvyzKZNV5kelU3ywENtyhOGwhu8Bs6Jru9EYKCyWA5smymWqYCpcq+yca7ps5z3N8dG4EdFSp0hpgiNCz1NM2CW8b8Zty5cEdrSM8BwTepGjNMH8ZARshjtl5jQAduDtYqEO0oHnp6qkw5yPZdjubkzywREJltK8zXIob3L6R0SqKmsy00LGn4mQPO/trObizy0TCLh+4/BXaGZuZd4IxyQvJ47MMSNi+IMKUy+Ra224z7q+7KXqH8Q7Ltygsg1xowZomvJuJqmWsYfF32wc+CyeCxtaI0tOtII9rdD702k1z1p8OROA714iAzARuou0F9LvO4F4+SwuDIqemCJISStkHGmaA2Y=
  - secure: rTPmppZEV257IyZLl/R8U5kvKq+o8T9YzuDq7iGVPZIiaagnritp8u+1LWz6+EB9qSMIsd95f/bn/BzcxAVRSzOC4WALVgtHoCAPe7owA9Ik3dxcZJ/Fpn3Km8sCElLeu4oTrmFlvZt8gAxfd6IZ62SuX4QIgC0+jhkesrKep6lF5/gqCQ3t5AmUbsktaxlsGK48uoZ7Te9bFVmJlXJXrmobA/j1tjq8bGTYWbQ5c3aFO7PxK4QJCZ83IzJfz7Mh14sdWRvDdcywgyLyaAhc4z6Gof+hWfyHTKDmRKpLHpsIRlcCG4VhMH3VSu2OEuOTEcHRuz/r3W9hy725n7CMDHfhonlwyoxHz/xUdvMdyT20my2QaUc+bNFvM+QpQv9u1FFRqpjWF3WX0ZqM2pF8381a+lPA/VIkJT3zmOPlC/1b9asIzq4KF1SR6gxZec1fNdq/mwL8VdmzfdKclJMY7HKJH2F3/NREb1Lq0X+2w0OK6j0BKQO4w0AWBoowgQIAFKTgHeR/ieAsjWfVtCv59ld2uVjCJfAsWUeC8XdGdC+TJNpIjcYWVJ1gRLUmlY5AblrJr8Qtm/tbEaITXQdrx4S8jjyJd4CJlfHAN+z5F9Sadns9XNpyu3EKG0j55ClTLdw89W6Ay55DBrAVj6hM/VHB5jpUxgF2ZAw7w+2JnEI=
