language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.3
  - android-25
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_62ed174ed142_key -iv $encrypted_62ed174ed142_iv
  -in obm.keystore.enc -out obm.keystore -d
install: ./gradlew clean
script: ./gradlew build
deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  api_key:
    secure: qkShQEWmLJZJow/TWHoxyGwNXKlAxKAx/aUwuOUOArkSWfTPg1EBmRNp5C4lht8TJunOppSjhS37AcLp1VPHggioh+YU1q3kkA+OxWpTeweEQOYTyI5FO64glH2dHHZXR/JrQ4GwGKw8CaAJXqqvTEXW6bFZY5U82sAgERmeCKL0/1rkF4x+NeqFF8/GUce2UGTOcQlsSDh7vefHEA6ga9FaTdIIBULvrMMMng0jSR9lg2i1MwQh8oXlMZXodL/4KLbF7f9PNqd+2YupuV4BMtOdNYHOv3t0ZLmiqfoziTKC6xjW2AZpMpZUBEkPlTjDsV9sBqiTuXxq2uJLSFzdeWgoiFcZvWwsrKzzyOg7F4lUkkrNd2ykVd0wORhbwpA6ndx+3mJz63bjPMdlFMQ/DY1Goy4eR8HFA1l8acaf7YRUMf8BM7fn5b9uFu7h2OLHSoz5gpUEEexnqcRVIgmIGAQDyRDOkDz8wn8qy0TonwTSkBS4VAlv3lnkCuLrHSdaKjVd58ryB+5rf1Y+MgEEUy1vtqDWk7IGldTBop290idKitRtFyhRF5hS5oFYDKwx2ivJ8ADu42HG2yNQmljLhrQL1rPSqcg+9tpsTqS7kWeWlhMC/2Dgau79QjqHeXUdclHzN+t6HwEdte8Uv2r0xNb6u/A76/BQu8py/mVyC2E=
  file: app/build/outputs/apk/app-release.apk
  on:
    repo: OpenBioMaps/android-app
env:
  global:
  - secure: psatpK785237wotIA53QXFDNJuzYYiT0/Do/9vzcq4QI+UaU4RT3Ldprg38DIVddixHC6D5xMzF1S7VrkzZA4pIwtnJbPKX0s08ihb+p0D94dD5g/Z6o+CmI5XZeZ2DVY2SBPg7rniJpdnGdSU1Q6ZU68b8Jtf6NX9jZZUuf2APdN5AAIC55S7Iag0I8xL9PrLRbFQ8mnjSu4uzjIRdRKlAI2ESEEoXe9KifjK2j5GpjB+06zT+Cg3tepl8y2gK+kyXvcbBLUhfl9fthTER3kv2s+3l6XIPXOpeR2L7xmTN0j4D7XCWp3Hv2ciVdMp6PijMySYq4IJLOxWWLIXVEvMZabDsKy1dscS3otdD1ikhMvITZkg5bbTFeE0XGw+9kXbZkv8p56YplBG2Row9coQtuIVI9b78dU/0nBdn1/9EVqrS28TSDhcCVSvZBeZIPWQcS+1FTEHBLGXf50KEt4xyjXv70bAeaIw4nny3wv6rhMkej4RoSQh6ybxbqsbu+Btw9DZEM3c8A6a7CaDjj+RnOdUfNNinwaHFQKRDuy6PkyApITy2qYuZ3SW+xYhyGVdytBt/V26QUXlMgjFff0iUaT/gz8VPe8TDwjYU2jQcnmAWMBjwxMkQ9LGDa7G1YBGAy3pza1i+Q++3g6cyzDze/Wc9VShiLMaZ4j/Zyl58=
  - secure: PWz7kf1D9d96WcL2GvxfHet/k/v0fOngPGAfk0diW8dPu2Uu9tZ6iKH8JJMqot8SxuwKXP0xvtyh9PMoxZP+LxWWaatmGYyX2ZenFBJxxIiGqNKpRnNpdOZZi9om90czFRSDfbEl9i/S69oDcsU4fgY5viTSovZTZEAvXPj4YjLu42DwR3fjHx7EAIwbezZ0TA8xcGxht8z24IBn8WEm9sCKdwFwSnBh4ioWNWUqinA+ri3unL6IDTBmKV40qphaDr4lgePLiCTKxkBMAAw5hRH5SrR5BxopkGHjP9EzZtwmfo4CdFbEPlNuX/bHrlSEoFGxbXLHe+krKJX/5c8A0ZtSPb1LMQ56E6nY0QZSZTKLsmdtSxnayTAHVbR9vBSgLyQd93cRkXnqNOC0vPD1zlDeQjRslSpfCYiF/1/L5qtH7cgyeY58Yrbfp9p1hWQy8lbZ0+YZK+tvPi/3dkUPdO2Gvbq0faBBVlIc2fwz84ZDy0xZ3uBybyp+EoJMeivftXltKqhfKpLjId5otlXihDSXcXoLgwe6kpx5Oz3gNGjX7Q3qMLsFjGFe2XLpiMsrb70CqsrY1xyfZ6vLUOLIaGVt7SIgfyPRugRoMACchVNQYjnG30RHJnLeQv9IUYGMUhIqNmkMge+3nb0rq9xjTMMVfBR53a/6X4SL4nHIfXY=
  - secure: j0OgTDMXp4zWtHVxZedHTKP9YpfWofl5C9QxFBzErNByMXwj1tmE4DeOFqUnVBJtMOt6ecLXSa+CbNZZyt6ei7rJLBwCaDA3nZsndPbHTTenz+j4Ru78pXpddUHNQZOx+1gJwzavLv2Y/tO0J0xdMFlsIMSy2HtBbvKonGlAnxhb9Fti6caaXo7C66uwEIAv7bys5FyD1NFgpvYpNxyPu2fIEmHBuGPeC6Xa8FtPgh41at29TvaWK69A8EvoeCMZHyM4Z3qBMPSoKaWgVFxjmfANNv2QVnskE1XexO7mWR8CF5vEG468ny1dZMsM0vbZOVEnuIK/9S1jRHstGLVz5P+VUJ4zz/YFG0+NriCj5BLNbYe3org8h7e7OM6MC8lKgnz9ob8e+yguePBX2ANTUW9D5FMSxBzrjTSmq2kN02HFS1BME1h3/vVhPDAFsewMoxA6bvNmUryoNAXxmARGlLOC1rbc0zPYdqht9zz60sZluUBS3uwB6sWBkO4W8k+ip/0jNs7+Tfq3Fvm4drOeIzkH/yytK8tDUJNj4Sd8SHXCCC6CDJKe1tXC34/wyykQspZRzz5ScXDVpn90Bib3ZXfts77z7YUqf/9xhl86pj7zIinuuMbPLYh3TXbJjxTKl8qdt5gpo03McPRu9nuQ6/moNdwQXP1aySKrAB8yEHw=
